### PR TITLE
Table Fix

### PR DESCRIPTION
**Pull request by darkdarcool**
Made you a table so you don't have to look at your ugly(sorry) list!

### CODE REVIEW

**Comment by iop3** [comment]
lmao i was about to do the same thing but u made the pr first >:(

**Comment by darkdarcool** [comment]
haha, hey, can you help me get out chitchat?

**Comment by darkdarcool** [comment]
I needed some people to help me test it out with the new version

**Comment by iop3** [comment]
sure! what can i do ?

**Comment by darkdarcool** [comment]
I invited you! I'll tell you there

**Comment by darkdarcool** [comment]
(also your repl username was hard to find, but I got it)

**Comment by kokonut27** [comment]
@darkdarcool - lmfao, thanks!

**Review by kokonut27 — APPROVED** [review]
good and approving

**Comment by darkdarcool** [comment]
lol, also jb, can you help me test!

**Comment by kokonut27** [comment]
uh, im busy rn, maybe later? sorry!

**Comment by darkdarcool** [comment]
ok!

**Comment by darkdarcool** [comment]
also @IcingHackz, if you can't find the ping, https://replit.com/@darkdarcool/ChitChat

**Comment by iop3** [comment]
ok thanks!

**Comment by iop3** [comment]
can i do it a bit later cuz im currently in class :P

**Comment by darkdarcool** [comment]
ok. Just tell me when you're on

**Pull request merged**
